title: Memory app
description: Memory is a desktop app which lets you instantly search through your web apps and browser history
sitename: Your Website
baseurl: '/one-page-wonder-jekyll'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME