title: Memory app
description: Memory is a desktop app which lets you instantly search through your web apps like Jira, Google docs and your browser history
sitename: Memory
baseurl: ''
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME